miSpoty/formulario/urls.py
from django.urls import include,path
from django.contrib import admin
from .models import *
from .views import *
from django.contrib.auth import authenticate, login

from formulario import views

app_name = "formulario"
urlpatterns = [
    path("registro/", views.SignUp.as_view(), name="registro"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.LogOut.as_view(), name="logout"),

]

miSpoty/miSpoty/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('music.urls')),
    path('admin/', admin.site.urls),
    path('',include('formulario.urls'   )),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miSpoty/music/urls.py
from django.urls import path
from .models import *
from .views import *
from music import views

app_name = "music"
urlpatterns=[

    path('',home, name="home") ,
    path('cancionesPopulares/', cancionesPopulares),
    path('player/',playerMusic),
    path("Artista/",views.crearArtista.as_view(),name="addArtista"),
]

miSpoty/formulario/models.py
from django.db import models

# Create your models here.

miSpoty/music/models.py
from django.db import models



# Create your models here.
"""
Definiciones de apoyo para poder tener las imagenes y las
canciones
"""
def image_directory_path(instance, filename):
    """Get song directory path to save."""

    return f"artists/images/{instance.id}_{instance.name}_{filename}"

def song_directory_path(instance, filename):
    """Get song directory path to save."""

    return f"music/songs/{instance.id}_{instance.name}_{filename}"


class Artist(models.Model):
    """Artist Model."""

    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to=image_directory_path, max_length=100)

    def __str__(self):
        """Get str representation."""
        return self.name

    def __repr__(self):
        """Get str representation."""
        return self.__str__()




class Song(models.Model):
    """Song Model."""

    name = models.CharField(max_length=200)
    song_file = models.FileField(null=True, upload_to=song_directory_path)

    # Relations
    artists = models.ManyToManyField("music.Artist", related_name="songs")

    def __str__(self):
        """Get str representation."""
        artists_str = ""
        artists = list(self.artists.all())
        if len(artists) == 0:
            return f"{self.name}"
        artists_str = f"{artists[0].name}"
        for artist in artists[1:]:
            artists_str += f", {artist.name}"
        return f"{self.name} by {artists_str}"

    def __repr__(self):
        """Get str representation."""
        return self.__str__()

miSpoty/formulario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.db import models
from django import forms

from .models import *

class SingUpForm(forms.Form):
    primer_nombre=forms.CharField(max_length=200)
    apellido=forms.CharField(max_length=200)
    email=forms.EmailField(max_length=200)
    password=forms.CharField(widget=forms.PasswordInput())
    def clean_email(self):
        """Validate that the email doesn't exist in the database."""
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).count() > 0:
            raise forms.ValidationError("El email ya existe .")
        return data


class LoginForm(AuthenticationForm):
    """Login form."""

    def clean(self):
        """Validate data.
        Validating all fields.
        """
        username = self.data["username"]
        password = self.data["password"]

        if User.objects.filter(username=username).count() == 0:
            self.add_error(
                "username", forms.ValidationError("El email no existe.")
            )

miSpoty/music/forms.py
"""Users forms."""
# Django
from django import forms
from django.contrib.auth.models import *
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate

class crearArtista(forms.Form):
    name = forms.CharField(max_length=200)
    image = forms.ImageField()

    def clean_name(self):
        data = self.cleaned_data["name"]
        if Artist.objects.filter(name=data).count() > 0:
            raise forms.ValidationError("El artista ya existe")

        return data

miSpoty/formulario/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from formulario.forms import SingUpForm, LoginForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login,logout


# Create your views here.
class SignUp (View):
    template= "formulario/Registro.html"
    """Nuevo usuario."""
    def get(self, request):

        """Render sign up form."""
        form = SingUpForm()
        context = {"form": form}
        return render(request, self.template, context)

    def post(self, request):


        """Receive and validate sign up form."""
        form = SingUpForm(request.POST)
        ##print(from.is_valid())
        if not form.is_valid():
            print("Entre a este caso y el error es este")
            print(form.errors)
            context = {"form": form}
            return render(request, self.template, context)

        new_user = User.objects.create_user(
        username=form.cleaned_data["email"],
        email=form.cleaned_data["email"],
        password=form.cleaned_data["password"],
        first_name=form.cleaned_data["primer_nombre"],
        last_name=form.cleaned_data["apellido"],
        )
        print("Ganamos")
        return HttpResponse("<h1>usuarioCreado!</h1>")


class Login(View):
    """New User Sign Up."""

    template = "formulario/Login.html"

    def get(self, request):
        """Render sign up form."""
        form = LoginForm()
        context = {"form": form}
        return render(request, self.template, context)

    def post(self, request):
        """Receive and validate sign up form."""
        form = LoginForm(data=request.POST)

        if not form.is_valid():
            context = {"form": form}
            return render(request, self.template, context)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"],
        )
        login(request, user)

        return HttpResponse("<h1>User logged!</h1>")

class LogOut(View):
    """docstring for ."""
    def get(self,request):
        logout(request)
        return redirect ("music:home")

miSpoty/music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import *
from django.views import View
from music.forms import crearArtista
from django.http import HttpResponse
from django.contrib.auth.models import *
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index (request):
    return HttpResponse("Bienvenidos")

def home(request):
    context={}
    return render(request,'music/home.html',context)

def cancionesPopulares(request):
    if request.method == 'GET':
        songs = Song.objects.all()
        to_play_id = request.GET.get("to_play", 1)
        songs_to_play = Song.objects.filter(id=to_play_id)
        if songs_to_play.count() == 0:
            to_play = Song.objects.first()
        else:
            to_play = songs_to_play.first()

        context = {"songs": songs, "to_play": to_play}
        return render(request, 'music/index.html', context)

def playerMusic(request):
    context={}
    return render(request,'music/player.html',context)


class crearArtista(View):
    def get(self, request):
        form = crearArtista()
        context = {"form": form}
        return render(request, 'music/Artista.html', context)
    def post(self, request):
        form = crearArtista(request.POST, request.FILES)
        print(form)
        if not form.is_valid():
            context = {"form": form}
            return render(request, 'music/Artista.html', context)
        Artist.objects.create(
        name=form.cleaned_data["name"],
        image=form.cleaned_data["image"],)
        return render(request, 'music/home.html')


def get(self, request):
        """GET method."""
        form=Artist()
        context={"form":form}
        return render(request, self.template,context)

miSpoty/formulario/templates/formulario/Artista.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Registro Artista</title>
  </head>
  <body>
    {% block body_content %}
    <form  action="." method="post">
      {% csrf_token %}
      
    </form>
    {% endblock body_content %}

  </body>
</html>

miSpoty/formulario/templates/formulario/Login.html
{% block body_content %}
<h1>Login</h1>
<form action="." method="POST">
    {% csrf_token %}

    <div class="sing_up_input">
        {{ form.username.errors }}
        <label for="username">Email:</label>
        {{ form.username }}
    </div>
    <div class="sing_up_input">
        {{ form.password.errors }}
        {{ form.password.label_tag }}
        {{ form.password }}
    </div>
    <input value="Sign up" type="submit">
</form>
<a href="{% url 'formulario:login' %}">Sign up</a>
{% endblock body_content %}

miSpoty/formulario/templates/formulario/Registro.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Registro</title>
  </head>
  {% block body_content %}
  <body>

    <h1>Entrar</h1>

    {% for field in form %}
    <div class="sing_up_input">
      <form class="" action="." method="post">
        {% csrf_token %}
        {{ fielf.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>

    {% endfor %}

<!--
    <form action="." method="POST">
        <label for="primer_nombre">Primer Nombre:</label><input name="primer_nombre" type="text">
        <label for="apellido">apellido:</label><input name="apellido" type="text">
        <label for="email">Email:</label><input name="email" type="email">
        <label for="password">Password:</label><input name="password" type="password">

    </form>-->
    <input value="Sign up" type="submit">
  </form>
  </body>
  {% endblock body_content %}
</html>

miSpoty/music/templates/music/Artista.html
{% block body_content %}
<h1>Crea artista</h1>
<form action="" method="POST" enctype="multipart/form-data" >
 {% csrf_token %}
   {% for field in form %}
   <div class="Artista">
       {{ field.label_tag }}
       {{ field }}
     {{ field.errors }}

   </div>
   {% endfor %}
   <input value="Agregar" type="submit">
</form>

<br>
{%include 'music/player.html' %}
{% endblock body_content %}

miSpoty/music/templates/music/home.html
<!DOCTYPE html>

{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Documentos</title>
    <link rel="stylesheet" type="text/css" href="{%  static 'css/index.css'  %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/player.css'  %}">
  </head>
  <body>



      <header>
          {% if user.is_authenticated %}
          <p>Welcome, {{ user.first_name }}.</p>
          <a href="{% url 'formulario:logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'formulario:login' %}">Login</a> or <a href="{% url 'formulario:registro'%}">Sign Up</a>
          {% endif %}
      </header>
      {% block body_content %}
      {% endblock body_content %}

    Este es el home de la practica
    <div class="img1">
        <img src= "{% static 'img/mp3.png' %}" alt="" width="20%" height="20%" >
    </div>


    <div class="posicionRelativa">
      <br>
      <br>
        {%include 'music/player.html'%}
    </div>
  </body>
</html>

miSpoty/music/templates/music/index.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{%block titlte%} Top song {% endblock%} </title>


      <link rel="stylesheet" type="text/css" href="{%  static 'css/index.css'  %}">
  </head>
  <body>
    <div class="titulo">
        <h1>Canciones chidas :)</h1>
    </div>
    <p>Las mejores canciones del momento</p>
    <div class="contenedor">
      <div class="seccionMusica">
        Hola como estassaflñfdmñsfdsf,sdf.fafmmsdfmfsldfm
        <ul class="tabla">
		        {% for song in songs  %}
		        	<li>{{song}}  <a href="../../../media/{{song.song_file}}">{{song.song_file}}</a>   </li>	
		        {% endfor %}
		    </ul>
       </div>
      <div class="imagenMedio">
        <img src="{% static 'img/pikachu.png' %}"  width="50%" height="100%">
      </div>

      <div class="lateralIzquierdo">
        que bueno
      </div>

    </div>
    <div class="posicionRelativa">
      <br>
      <br>
      <br>
      <br>
    {%include 'music/player.html' %}
    </div>


  </body>
</html>

miSpoty/music/templates/music/player.html
{% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{%  static 'css/reproductor.css'  %}">

</head>
<div class="ejemplo">
  Este es mi reproductor
</div>


<div class="reproductor">
  <audio controls="controls">
  <source src="track.ogg" type="audio/ogg" />
  <source src="track.mp3" type="audio/mpeg" />
</audio>

</div>